version: 2.1

jobs:
  build:
    environment:
      PATH: "/home/circleci/.asdf/bin:/home/circleci/.asdf/shims:/usr/bin:/bin:/usr/sbin:/sbin"
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - restore_cache:
          keys:
            - circle_sample-asdf
      - run: if ! command -v asdf; then git clone https://github.com/HashNuke/asdf.git ~/.asdf; fi
      - run: asdf plugin-add erlang https://github.com/HashNuke/asdf-erlang.git
      - run: asdf plugin-add elixir https://github.com/HashNuke/asdf-elixir.git
      - run: asdf install
      - run: mix local.rebar --force
      - save_cache:
          key: circle_sample-asdf
          paths:
            - ~/.asdf
      - restore_cache:
          keys:
            - circle_sample-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: yes | mix deps.get
      - save_cache:
          key: circle_sample-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - run: mix coveralls.circle

workflows:
  ci:
    jobs:
      - build
